spring.application.name=WallE_V2


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/WallEV1


#hibernate specific properties
# to inform hibernate whether the table has to be created or updated
spring.jpa.hibernate.ddl-auto=update
# to see the generated sql statements
spring.jpa.show-sql=true

